name: Build Docker Image
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    
jobs:
  #build_docker_image:
  #  name: Build Image
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - name: Checkout repo
  #      uses: actions/checkout@v2

  #    - name: SSH Agent init
  #      uses: webfactory/ssh-agent@v0.5.2
  #      with:
  #        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #    - name: Getting deps from host
  #      run: ./rebar3 get-deps

  #    - name: Building and publishing an image
  #      uses: docker/build-push-action@v1
  #      with:
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #        registry: ghcr.io
  #        repository: t0ha/cryptoring-poloniex
  #        tag_with_ref: true

  deploy_to_kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-18.04
    #needs: build_docker_image
    env:
      RABBIT_USER: cryptoring
      RABBIT_VHOST: "/"
      COUCHDB_URL: "https://392550bc-ca75-4cde-8d0c-1b0126c80727-bluemix:ce44fad87976d433f3830521df8c1cc24e2a72e3026d8874b051344649436572@392550bc-ca75-4cde-8d0c-1b0126c80727-bluemix.cloudantnosqldb.appdomain.cloud"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.6.0
        with:
            kubectl: '1.17.1'
            kustomize: '3.7.0'
            helm: '2.16.7'
            helmv3: '3.5.3'

      - name: Install Helm Package
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          helmv3 version
          helmv3 upgrade --install poloniex -n cryptoring ./ops/helmchart/  --values ./ops/helmchart/values.yaml
