name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
  build_docker_image:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
      - name: Work directory
        run: pwd
      - name: ls
        run: |
          ls

      - name: Building image
        shell: bash
        run: docker build -t poloniex .

