name: Build Docker Image
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    
jobs:
  build_docker_image:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Building and publishing an image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: t0ha/poloniex.erl/cryptoring-poloniex
          tag_with_ref: true

